FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel
# FROM nvidia/cuda:12.6.1-cudnn-devel-ubuntu24.04
# FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get update -y \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  curl \
  ca-certificates \
  nvtop htop btop \
  sudo \
  git \
  bzip2 \
  libx11-6 \
  locales \
  man \
  nano \
  git \
  procps \
  openssh-client \
  ffmpeg libsm6 libxext6 \ 
  vim \
  lsb-release \
  build-essential \
  && rm -rf /var/lib/apt/lists/* \
  && sed -i "s/# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen \
  && locale-gen \
  && mkdir /projects

ENV LANG=en_US.UTF-8 \
    HOME=/projects \
    ARCH=amd64 \
    # EXTENSIONS_GALLERY="{\"serviceUrl\":\"https://marketplace.visualstudio.com/_apis/public/gallery\",\"itemUrl\":\"https://marketplace.visualstudio.com/items\"}" \
    CODE_SERVER_VERSION=4.92.2

# Install code-server
WORKDIR /projects
RUN curl -fOL https://github.com/cdr/code-server/releases/download/v${CODE_SERVER_VERSION}/code-server_${CODE_SERVER_VERSION}_${ARCH}.deb \
  && dpkg -i ./code-server_${CODE_SERVER_VERSION}_${ARCH}.deb \
  && rm ./code-server_${CODE_SERVER_VERSION}_${ARCH}.deb

EXPOSE 8080
ENTRYPOINT ["/usr/bin/code-server", "--bind-addr", "0.0.0.0:8080", "--disable-telemetry", "."]